# Generated by Django 6.1.1 on 2026-09-19 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('EMI_REMINDER', 'EMI Reminder'), ('LOAN_OVERDUE', 'Loan Overdue'), ('BUDGET_ALERT', 'Budget Alert'), ('RECURRING_TRANSACTION', 'Recurring Transaction'), ('MONTHLY_SUMMARY', 'Monthly Summary'), ('CUSTOM_REMINDER', 'Custom Reminder')], max_length=25)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('dedupe_key', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='notificatio_user_id_f2ad08_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'dedupe_key'), name='unique_notification_per_user_event')],
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('LOAN_EMI', 'Loan EMI'), ('CREDIT_CARD', 'Credit Card'), ('INSURANCE', 'Insurance'), ('RENT', 'Rent'), ('ELECTRICITY', 'Electricity'), ('RECURRING_EXPENSE', 'Recurring Expense'), ('FINANCIAL_GOAL', 'Financial Goal'), ('CUSTOM', 'Custom')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('reminder_date', models.DateField()),
                ('recurrence', models.CharField(choices=[('NONE', 'None'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='NONE', max_length=10)),
                ('is_completed', models.BooleanField(default=False)),
                ('snoozed_until', models.DateField(blank=True, null=True)),
                ('last_notified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('reminder_date',),
                'indexes': [models.Index(fields=['user', 'is_completed', 'reminder_date'], name='notificatio_user_id_1c96da_idx')],
            },
        ),
    ]
