# Generated by Django 6.1.1 on 2026-09-20 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('EMI_REMINDER', 'EMI Reminder'), ('LOAN_OVERDUE', 'Loan Overdue'), ('BUDGET_ALERT', 'Budget Alert'), ('RECURRING_TRANSACTION', 'Recurring Transaction'), ('MONTHLY_SUMMARY', 'Monthly Summary'), ('CUSTOM_REMINDER', 'Custom Reminder'), ('STALE_INVESTMENT_PRICE', 'Stale Investment Price')], max_length=25),
        ),
    ]
