# Generated by Django 6.1.1 on 2026-09-19 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('goal_type', models.CharField(choices=[('EMERGENCY_FUND', 'Emergency Fund'), ('EDUCATION', 'Education'), ('VEHICLE', 'Vehicle'), ('HOUSE', 'House'), ('VACATION', 'Vacation'), ('CUSTOM', 'Custom Goal')], max_length=20)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('target_date', models.DateField()),
                ('monthly_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('ABANDONED', 'Abandoned')], default='IN_PROGRESS', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('target_date',),
            },
        ),
        migrations.CreateModel(
            name='GoalContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('contribution_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='goals.financialgoal')),
            ],
            options={
                'ordering': ('-contribution_date', '-created_at'),
            },
        ),
        migrations.AddIndex(
            model_name='financialgoal',
            index=models.Index(fields=['user', 'status'], name='goals_finan_user_id_cd3e92_idx'),
        ),
        migrations.AddConstraint(
            model_name='financialgoal',
            constraint=models.CheckConstraint(condition=models.Q(('target_amount__gt', 0)), name='goal_target_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='financialgoal',
            constraint=models.CheckConstraint(condition=models.Q(('current_amount__gte', 0)), name='goal_current_amount_non_negative'),
        ),
        migrations.AddIndex(
            model_name='goalcontribution',
            index=models.Index(fields=['goal', 'contribution_date'], name='goals_goalc_goal_id_0efb2a_idx'),
        ),
        migrations.AddConstraint(
            model_name='goalcontribution',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='goal_contribution_amount_positive'),
        ),
    ]
