# Generated by Django 6.1.1 on 2026-09-16 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_name', models.CharField(max_length=100)),
                ('loan_type', models.CharField(choices=[('PERSONAL', 'Personal'), ('HOME', 'Home'), ('VEHICLE', 'Vehicle'), ('EDUCATION', 'Education'), ('CREDIT_CARD', 'Credit Card'), ('BUSINESS', 'Business'), ('OTHER', 'Other')], max_length=20)),
                ('lender', models.CharField(blank=True, max_length=100)),
                ('original_principal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('outstanding_principal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('annual_interest_rate', models.DecimalField(decimal_places=3, max_digits=6)),
                ('interest_calculation_method', models.CharField(choices=[('DAILY_REDUCING_BALANCE', 'Daily Reducing Balance'), ('MONTHLY_REDUCING_BALANCE', 'Monthly Reducing Balance'), ('EMI_AMORTIZATION', 'EMI Amortization'), ('FLAT_RATE', 'Flat Rate')], max_length=30)),
                ('emi_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('payment_frequency', models.CharField(choices=[('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Biweekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=10)),
                ('start_date', models.DateField()),
                ('maturity_date', models.DateField()),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('processing_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('late_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('prepayment_penalty', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('OVERDUE', 'Overdue'), ('PAUSED', 'Paused')], default='ACTIVE', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'status'], name='loans_loan_user_id_d0fb34_idx'), models.Index(fields=['user', 'next_due_date'], name='loans_loan_user_id_259c45_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('original_principal__gt', 0)), name='loan_original_principal_positive'), models.CheckConstraint(condition=models.Q(('outstanding_principal__gte', 0)), name='loan_outstanding_principal_non_negative'), models.CheckConstraint(condition=models.Q(('annual_interest_rate__gte', 0)), name='loan_interest_rate_non_negative'), models.CheckConstraint(condition=models.Q(('maturity_date__gt', models.F('start_date'))), name='loan_maturity_after_start')],
            },
        ),
    ]
