# Generated by Django 6.1.1 on 2026-09-16 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
        ('transactions', '0002_recurringtransaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('principal_component', models.DecimalField(decimal_places=2, max_digits=14)),
                ('interest_component', models.DecimalField(decimal_places=2, max_digits=14)),
                ('late_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('extra_payment', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('remaining_principal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('transaction_reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='loans.loan')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_payments', to='transactions.transaction')),
            ],
            options={
                'ordering': ('-payment_date', '-created_at'),
                'indexes': [models.Index(fields=['loan', 'payment_date'], name='loans_loanp_loan_id_7ae122_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='loan_payment_amount_positive')],
            },
        ),
    ]
