# Generated by Django 6.1.1 on 2026-09-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_loanpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='priority_order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
