# Generated by Django 6.1.1 on 2026-09-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_loan_priority_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_type',
            field=models.CharField(choices=[('PERSONAL', 'Personal'), ('HOME', 'Home'), ('VEHICLE', 'Vehicle'), ('EDUCATION', 'Education'), ('CREDIT_CARD', 'Credit Card'), ('BUSINESS', 'Business'), ('GOLD_LOAN', 'Gold Loan'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
