# Generated by Django 6.1.1 on 2026-09-19 14:38

import apps.budgets.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('year', models.PositiveIntegerField()),
                ('alert_thresholds', models.JSONField(default=apps.budgets.models.default_alert_thresholds)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-year', '-month', 'category'),
                'indexes': [models.Index(fields=['user', 'month', 'year'], name='budgets_bud_user_id_8e3844_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='budget_amount_positive'), models.UniqueConstraint(fields=('user', 'category', 'month', 'year'), name='unique_budget_per_category_month')],
            },
        ),
    ]
