export const REMINDER_TYPES = [
  'LOAN_EMI', 'CREDIT_CARD', 'INSURANCE', 'RENT', 'ELECTRICITY',
  'RECURRING_EXPENSE', 'FINANCIAL_GOAL', 'CUSTOM',
]

export const RECURRENCES = ['NONE', 'DAILY', 'WEEKLY', 'MONTHLY', 'YEARLY']
