# Generated by Django 6.1.1 on 2026-09-19 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('symbol', models.CharField(blank=True, max_length=30)),
                ('investment_type', models.CharField(choices=[('STOCK', 'Stock'), ('MUTUAL_FUND', 'Mutual Fund'), ('ETF', 'ETF'), ('BOND', 'Bond'), ('FIXED_DEPOSIT', 'Fixed Deposit'), ('GOLD', 'Gold'), ('CRYPTO', 'Crypto'), ('REAL_ESTATE', 'Real Estate'), ('OTHER', 'Other')], max_length=20)),
                ('platform', models.CharField(blank=True, max_length=100)),
                ('quantity', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('average_buy_price', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('total_invested', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('realized_profit_loss', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('dividend_income', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('current_price', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('current_price_updated_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investments', to='goals.financialgoal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='InvestmentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('DIVIDEND', 'Dividend'), ('BONUS', 'Bonus'), ('SPLIT', 'Split'), ('FEE', 'Fee'), ('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal')], max_length=12)),
                ('transaction_date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('price', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('fees', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='investments.investment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-transaction_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='PortfolioSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField()),
                ('total_invested', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('portfolio_value', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('cash_value', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('profit_loss', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('dividend_income', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-snapshot_date',),
            },
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['user', 'status'], name='investments_user_id_352b49_idx'),
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['user', 'investment_type'], name='investments_user_id_7f7723_idx'),
        ),
        migrations.AddConstraint(
            model_name='investment',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='investment_quantity_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='investment',
            constraint=models.CheckConstraint(condition=models.Q(('average_buy_price__gte', 0)), name='investment_avg_buy_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='investment',
            constraint=models.CheckConstraint(condition=models.Q(('current_price__gte', 0)), name='investment_current_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='investment',
            constraint=models.CheckConstraint(condition=models.Q(('total_invested__gte', 0)), name='investment_total_invested_non_negative'),
        ),
        migrations.AddIndex(
            model_name='investmenttransaction',
            index=models.Index(fields=['user', 'transaction_date'], name='investments_user_id_3e38e8_idx'),
        ),
        migrations.AddIndex(
            model_name='investmenttransaction',
            index=models.Index(fields=['investment', 'transaction_date'], name='investments_investm_383447_idx'),
        ),
        migrations.AddConstraint(
            model_name='investmenttransaction',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='investment_txn_quantity_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='investmenttransaction',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='investment_txn_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='investmenttransaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='investment_txn_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='investmenttransaction',
            constraint=models.CheckConstraint(condition=models.Q(('fees__gte', 0)), name='investment_txn_fees_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='investmenttransaction',
            constraint=models.CheckConstraint(condition=models.Q(('tax__gte', 0)), name='investment_txn_tax_non_negative'),
        ),
        migrations.AddIndex(
            model_name='portfoliosnapshot',
            index=models.Index(fields=['user', 'snapshot_date'], name='investments_user_id_fe8db4_idx'),
        ),
        migrations.AddConstraint(
            model_name='portfoliosnapshot',
            constraint=models.UniqueConstraint(fields=('user', 'snapshot_date'), name='unique_portfolio_snapshot_per_user_day'),
        ),
    ]
