# Generated by Django 6.1.1 on 2026-09-20 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('ON_HOLD', 'On Hold'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=10),
        ),
    ]
