# Generated by Django 6.1.1 on 2026-09-19 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loans', '0003_loan_priority_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RepaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.CharField(choices=[('AVALANCHE', 'Avalanche'), ('SNOWBALL', 'Snowball'), ('CUSTOM', 'Custom')], max_length=10)),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=14)),
                ('essential_expenses', models.DecimalField(decimal_places=2, max_digits=14)),
                ('emergency_savings_allocation', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('extra_payment', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_existing_emi', models.DecimalField(decimal_places=2, max_digits=14)),
                ('months_remaining', models.PositiveIntegerField()),
                ('expected_payoff_date', models.DateField()),
                ('total_interest', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_payment', models.DecimalField(decimal_places=2, max_digits=14)),
                ('assumptions', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayment_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_number', models.PositiveIntegerField()),
                ('month_date', models.DateField()),
                ('loan_name', models.CharField(max_length=100)),
                ('normal_emi', models.DecimalField(decimal_places=2, max_digits=14)),
                ('extra_payment', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('principal_paid', models.DecimalField(decimal_places=2, max_digits=14)),
                ('interest_paid', models.DecimalField(decimal_places=2, max_digits=14)),
                ('closing_balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('loan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_items', to='loans.loan')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='planning.repaymentplan')),
            ],
            options={
                'ordering': ('month_number', 'loan_name'),
            },
        ),
        migrations.AddIndex(
            model_name='repaymentplan',
            index=models.Index(fields=['user', '-created_at'], name='planning_re_user_id_de16f6_idx'),
        ),
        migrations.AddIndex(
            model_name='planitem',
            index=models.Index(fields=['plan', 'month_number'], name='planning_pl_plan_id_71cb33_idx'),
        ),
    ]
